require_relative 'movement_rules/castling_board_control.rb'
require_relative 'movement_rules/castling_piece_control.rb'
require_relative 'movement_rules/castling_rights.rb'
require_relative 'movement_rules/en_passant_board_control.rb'
require_relative 'movement_rules/en_passant_piece_control.rb'
require_relative 'movement_rules/move_slide_pattern.rb'
require_relative 'movement_rules/move_step_pattern.rb'